### ISSUE TITLE
Building stops on mktables.py

### ISSUE THREAD

**Issue by ggnkua** [christianparpart/libunicode#2]
Trying to build the library as a part of contour, and the build stops with the error message:

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\contour\\3rdparty\\libunicode\\src\\unicode/../../docs/ucd/PropertyValueAliases.txt'
```

The whole ```docs``` folder doesn't seem to be a part of the repo, I guess it was not added?

**Comment by christianparpart** [comment]
Please CD into 3rdparty/libunicode and then execute

`git reset --hard HEAD`

But don't close the ticket yet, as I would like to prevent that from happening in the future. :)

**Comment by christianparpart** [comment]
I think we can close this ticket now. `master` branch contains a cmake option to conditionally enable rebuilding Unicode tables (and API) if a path to an extracted UCD.zip was provided, otherwise a `make clean` will NOT kill the auto-generated files that are checked in to Git.
